// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  call_to_action: defineAsyncComponent(
    () => import("./CallToAction/index.vue")
  ),
  features: defineAsyncComponent(() => import("./Features/index.vue")),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  testimonials: defineAsyncComponent(() => import("./Testimonials/index.vue")),
  text_with_image: defineAsyncComponent(
    () => import("./TextWithImage/index.vue")
  ),
});
